//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntDeployWinform {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntDeployWinform.Models.resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Deploy!! 的本地化字符串。
        /// </summary>
        public static string ConfirmDeploy {
            get {
                return ResourceManager.GetString("ConfirmDeploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please input right days value 的本地化字符串。
        /// </summary>
        public static string DaysInvaild {
            get {
                return ResourceManager.GetString("DaysInvaild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to rollBack to Server: 的本地化字符串。
        /// </summary>
        public static string DeployRollBackConfirm {
            get {
                return ResourceManager.GetString("DeployRollBackConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to deploy to Server: 的本地化字符串。
        /// </summary>
        public static string DeployServerConfim {
            get {
                return ResourceManager.GetString("DeployServerConfim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 selected env have no server set yet 的本地化字符串。
        /// </summary>
        public static string EnvHaveNoServer {
            get {
                return ResourceManager.GetString("EnvHaveNoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 fire url is not correct! 的本地化字符串。
        /// </summary>
        public static string FireUrlInvaid {
            get {
                return ResourceManager.GetString("FireUrlInvaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 get current project skd version error 的本地化字符串。
        /// </summary>
        public static string GetNetCoreSdkVersionError {
            get {
                return ResourceManager.GetString("GetNetCoreSdkVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 netcore project can not use [FDD(runtime)] mode! 的本地化字符串。
        /// </summary>
        public static string NetcoreProjectPublishModeError {
            get {
                return ResourceManager.GetString("NetcoreProjectPublishModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 selected env have no linux server set yet! 的本地化字符串。
        /// </summary>
        public static string NoLinuxServer {
            get {
                return ResourceManager.GetString("NoLinuxServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 current project is not windows service project! 的本地化字符串。
        /// </summary>
        public static string NotServiceProject {
            get {
                return ResourceManager.GetString("NotServiceProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 current project is not web project! 的本地化字符串。
        /// </summary>
        public static string NotWebProject {
            get {
                return ResourceManager.GetString("NotWebProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 current project is not netcore project! 的本地化字符串。
        /// </summary>
        public static string NowNetcoreProject {
            get {
                return ResourceManager.GetString("NowNetcoreProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please input right port value 的本地化字符串。
        /// </summary>
        public static string PortValueInvaid {
            get {
                return ResourceManager.GetString("PortValueInvaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rollback Deploy!! 的本地化字符串。
        /// </summary>
        public static string RollBackConfirm {
            get {
                return ResourceManager.GetString("RollBackConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please select env! 的本地化字符串。
        /// </summary>
        public static string SelectEnv {
            get {
                return ResourceManager.GetString("SelectEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please select sdk type！ 的本地化字符串。
        /// </summary>
        public static string SelectSdkType {
            get {
                return ResourceManager.GetString("SelectSdkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please input serviceName! 的本地化字符串。
        /// </summary>
        public static string ServiceNameRequired {
            get {
                return ResourceManager.GetString("ServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 volume is not correct! 的本地化字符串。
        /// </summary>
        public static string VolumeInvaid {
            get {
                return ResourceManager.GetString("VolumeInvaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please input web site name! 的本地化字符串。
        /// </summary>
        public static string WebSiteNameRequired {
            get {
                return ResourceManager.GetString("WebSiteNameRequired", resourceCulture);
            }
        }
    }
}
