









// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by T4 Template.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Resources;

namespace AntDeploy
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    static class VSPackage
    {
        static readonly ResourceManager Resx = new ResourceManager("AntDeploy.VSPackage", typeof(VSPackage).Assembly);


        public static string _110 { get; } = Resx.GetString("110");

        public static string _112 { get; } = Resx.GetString("112");

        public static string EditMenuPattern { get; } = Resx.GetString("EditMenuPattern");

    }
}